### ISSUE TITLE
Martin gale não multiplica

### ISSUE THREAD

**Issue by patrickfinardi09** [RafaelMNogueira/IQOption_CopyTrader#1]
O sistema de martingale funciona, mas o valor mantem padrão quando é feito MG, não está multiplicando

**Comment by RafaelMNogueira** [comment]
Bom Dia, tudo blz ?
Então identifiquei o erro quando utilizado a opção "binário", já realizei a correção e incluir a opção da configuração da multiplicação por um valor fixo ou variável de acordo com o Payout. 
Qualquer dúvida estou a disposição.

**Comment by patrickfinardi09** [comment]
Ótimo, parabéns pelo trabalho, ficou muito bom o script 👍🏻

**Comment by RafaelMNogueira** [comment]
Vlw. 
Qualquer dúvida estou a disposição.
